
trigger:
- master

pool: "default"

variables:
- name: AzureSubscription
  value: 'Azure subscription 1(970fcef5-9c23-4f7d-a11b-5a96d104f066)'

- name: RG
  value: 'guro'

  # Resources
- name: RG_Location
  value: 'eastus'
- name: Vault
  value: '$(RG)KeyVault'
- name: AciName
  value: 'guroaciapi'
- name: AciImage
  value: 'guroregistry.azurecr.io/api:latest'
- name: AciPort
  value: '80'
- name: AppConfigEndpoint # Ont pourrait apporter la variable du premier pipeline ...
  value: 'https://guroappconfiguration.azconfig.io'  
- name: RegistryServer # Ont pourrait apporter la variable du premier pipeline ...
  value: 'guroregistry.azurecr.io'  
- name: RegistryUsername # Ont pourrait apporter la variable du premier pipeline ...
  value: 'guroRegistry'

- name: InfrastructureFolder
  value: 'DeployACI'

steps:
  - task: AzureKeyVault@2
    displayName: 'Reading Secrets'
    inputs:
      azureSubscription: $(AzureSubscription)
      KeyVaultName: 'GuroKeyVault'
      SecretsFilter: 'ClientID,TenantID,ClientSecret,ContainerRegistry'
      RunAsPreJob: false

  - task: AzureResourceManagerTemplateDeployment@3
    displayName: ACI API Deployment
    inputs:
      deploymentScope: 'Resource Group'
      azureResourceManagerConnection: $(AzureSubscription)
      action: 'Create Or Update Resource Group'
      resourceGroupName: '$(RG)'
      location: '$(RG_Location)'
      templateLocation: 'Linked artifact'
      csmFile: '$(Build.SourcesDirectory)\$(InfrastructureFolder)\azuredeploy.json'
      csmParametersFile: '$(Build.SourcesDirectory)\$(InfrastructureFolder)\azuredeploy.parameters.json'
      overrideParameters: '-AciName $(AciName) -AciImage $(AciImage) -AciPort $(AciPort) -AciClientId $(ClientID) -AciTenantId $(TenantID) -AciSecret $(ClientSecret) -AppConfigEndpoint $(AppConfigEndpoint) '
      deploymentMode: 'Incremental'
      deploymentOutputs: 'Deployment1'