# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool: "default"

variables:
  # Resource group ainsi que l'acronyme utiliser pour créer le nom des resources
- name: RG
  value: 'guro'

- name: AzureSubscription
  value: 'Azure subscription 1(970fcef5-9c23-4f7d-a11b-5a96d104f066)'

  # Resources
- name: RG_Location
  value: 'eastus'
- name: clusterName
  value: '$(RG)kube'
- name: dnsPrefix
  value: '$(RG)kube'
- name: agentCount
  value: 3
- name: agentVMSize
  value: "standard_d2s_v3"
- name: linuxAdminUsername
  value: "kubeadmin"
- name: sshRSAPublicKey

- name: InfrastructureFolder
  value: 'DeployKube'

steps:
  - task: AzureCLI@2
    inputs:
      azureSubscription: $(AzureSubscription)
      scriptType: 'ps'
      scriptLocation: 'inlineScript'
      inlineScript: |
        # Create an SSH key pair using Azure CLI
        az sshkey create --name "KubeSSHKey" --resource-group "guro"
        $key = $(az sshkey show --name "KubeSSHKey" --resource-group "guro" --query "publicKey" -- tsv)
        
        Write-Host $key
        Write-Host "##vso[task.setvariable variable=sshRSAPublicKey]$key"

  - task: AzureResourceManagerTemplateDeployment@3
    displayName: ARM Deployment Kube Cluster
    inputs:
      deploymentScope: 'Resource Group'
      azureResourceManagerConnection: $(AzureSubscription)
      action: 'Create Or Update Resource Group'
      resourceGroupName: '$(RG)'
      location: '$(RG_Location)'
      templateLocation: 'Linked artifact'
      csmFile: '$(Build.SourcesDirectory)\$(InfrastructureFolder)\azuredeploy.json'
      csmParametersFile: '$(Build.SourcesDirectory)\$(InfrastructureFolder)\azuredeploy.parameters.json'
      overrideParameters: '-clusterName $(clusterName) -location $(RG_Location) -dnsPrefix $(dnsPrefix) -agentCount $(agentCount) -agentVMSize $(agentVMsize) -linuxAdminUsername $(linuxAdminUsername) -sshRSAPublicKey $(sshRSAPublicKey)'
      deploymentMode: 'Incremental'
      deploymentOutputs: 'Deployment1'