services:
  mvc:
    build:
      context: .
      dockerfile: MVC/Dockerfile
    ports:
      - "7182:8080"
    networks:
        - app_vlan

  api:
    build:
      context: .
      dockerfile: API/Dockerfile
    ports:
      - "7101:443"
    networks:
        - app_vlan
    depends_on:
      mvc:
        condition: service_healthy

  worker_image:
    build:
      context: .
      dockerfile: Worker_Image/Dockerfile
    networks:
        - app_vlan
    depends_on:
      mvc:
        condition: service_healthy

  worker_content:
    build:
       context: .
       dockerfile: Worker_Content/Dockerfile
    networks:
        - app_vlan
    depends_on:
      mvc:
        condition: service_healthy

networks:
  app_vlan:
    driver: bridge